### ISSUE TITLE
本地时间不正确

### ISSUE THREAD

**Issue by jtsang4** [mingxiaoyu/N1Openwrt#15]
版本: [2022-02-12 15:32:09 / N1-Openwrt | 编译](https://github.com/mingxiaoyu/N1Openwrt/releases/tag/20220212)

`/etc/config/system` 中的配置为:
![Screenshot_20220218_061634](https://user-images.githubusercontent.com/17686135/154499968-d253e635-b474-44bd-bf99-2df4a87b315e.png)

`date -u` 显示的时间正确, `date -R` 始终是错误的时间，预期应该是 `date -R` 正确

**Comment by jtsang4** [comment]
在启动脚本中添加 `ntpd -n -q -p ntp.aliyun.com` 后，顺利完成了时间同步

**Comment by jtsang4** [comment]
后续发现网络里其它设备还是有无法同步时间的问题，最终定位为使用了 docker 版本的固件，同时使用了 fake-ip 的增强模式导致的问题，类似 https://github.com/vernesong/OpenClash/issues/1133 的问题，换成兼容模式以后可以同步时间了

**Comment by jtsang4** [comment]
使用自己构建的移除 docker  后的固件，问题已彻底解决，fake-ip 增强模式可以正常同步时间

https://github.com/jtsang4/N1Openwrt

**Comment by mingxiaoyu** [comment]
谢谢反馈
