### ISSUE TITLE
编译中的问题

### ISSUE THREAD

**Issue by doctor-design** [mingxiaoyu/N1Openwrt#2]
编译脚本中这句：“cp -r *.xz ${UPLOAD}/”是拷贝那个预编译工具链文件吗？这文件怎么上去的我这里怎么没有，执行到这句就出错，前面编译都没问题，就是到这出错白白浪费几个小时，往复了许多次，我临时注释掉了。可否加个判断没这个文件就不发布它。

**Comment by mingxiaoyu** [comment]
1. 是预编译工具链文件。
2. 可以加判断。明天吧
