### ISSUE TITLE
两个编译脚本的小bug

### ISSUE THREAD

**Issue by doctor-design** [mingxiaoyu/N1Openwrt#4]
如题，变量“DATE”没有赋值，虽不影响编译结果，但影响发布标题的完整。

**Comment by mingxiaoyu** [comment]
...谢谢。随便提下醒 luci-app-dockerman 现在不能编译。选了必出错

**Comment by doctor-design** [comment]
谢谢！原来是这样！的确我编译luci-app-dockerman出错了，我还找原因呢，不找了。

**Comment by mingxiaoyu** [comment]
luci-app-dockerman 可以编译过了。哈哈
