### ISSUE TITLE
N1_Multi 无法打包

### ISSUE THREAD

**Issue by mingxiaoyu** [mingxiaoyu/N1Openwrt#7]
这个是上游组件的多个打包的问题。。。。
周末没空修改
两个方案
1： 145 行       if: steps.package.outputs.status  == 'true' && env.RELEASE == 'true' && !cancelled()  删掉

2. 等N1_Multi  完成之后，通过 package.yml 进行打包。

如果仅仅打包N1   ，types: s905d 什么都不用改。

**Comment by mingxiaoyu** [comment]
如果不想自己打包。可以自己下载现成的。

**Comment by doctor-design** [comment]
package-flippy-openwrt   v1.0有个bug，获取内核那一段我加了一句：sudo rm -rf  kernel 后，N1_Multi多type编译和打包就都没问题了（我16号编译测试通过，出来的固件有没有问题我就不知道了，因为我也没有别的设备测试）。
我当时也调用过大佬的v2.0编译确实有问题。
我之所以没升级2.0 是因为1.0勉强可以看懂一些，出了错可以谷歌解决，2.0就完全看不懂了.....

**Comment by doctor-design** [comment]
补充：打包出错是在换内核的时候，中文大概意思是：调用已是其他工作区的副本......
谷歌出来都说是上次编译有东西没释放出来，被占用，需要删掉.....
但是删哪个文件？路径是什么？完全就不知道了.....试了无数次才是现在这个样子。反正编译出来了。。。

**Comment by mingxiaoyu** [comment]
@doctor-design https://github.com/mingxiaoyu/package-flippy-openwrt/runs/3101506425?check_suite_focus=true
看下 ，我分支下的shell 版本。没有你说的那个问题。

**Comment by doctor-design** [comment]
@mingxiaoyu
这是注释掉那一条之后的：
https://github.com/doctor-design/N1Openwrt/runs/3109709622?check_suite_focus=true
换内核时：
2021-07-20 01:14:40 (151 MB/s) - ‘/opt/openwrt/openwrt-armvirt-64-default-rootfs.tar.gz’ saved [149465469/149465469]

svn: E155000: '/home/runner/work/N1Openwrt/N1Openwrt/kernel' is already a working copy for a different URL
========================= begin ./mk_s905d_n1.sh ===========================
/opt/kernel/modules-5.13.2-flippy-62+.tar.gz not exists!
打包结果外面是看不出来出错的。以上是打包脚本。

编译脚本正在运行，还没出结果（等几小时后）

**Comment by mingxiaoyu** [comment]
5.13.2-flippy-62+

这个内核文件没有

**Comment by doctor-design** [comment]
有的，成功过的。看我刚又加上那句后打包个成功的
https://github.com/doctor-design/N1Openwrt/runs/3109828724?check_suite_focus=true

2021-07-20 01:38:23 (56.0 MB/s) - ‘/opt/openwrt/openwrt-armvirt-64-default-rootfs.tar.gz’ saved [149465469/149465469]

A    kernel/boot-5.10.50-flippy-62+.tar.gz
A    kernel/dtb-allwinner-5.10.50-flippy-62+.tar.gz
A    kernel/dtb-amlogic-5.10.50-flippy-62+.tar.gz
A    kernel/dtb-rockchip-5.10.50-flippy-62+.tar.gz
A    kernel/modules-5.10.50-flippy-62+.tar.gz
Checked out revision 125.
========================= begin ./mk_s905d_n1.sh ===========================
Use /opt/openwrt/openwrt-armvirt-64-default-rootfs.tar.gz as openwrt rootfs!
check mkfs.btrfs ok
check mkfs.vfat ok

v1.0 不能用参数latest+，只能用全名传递

**Comment by doctor-design** [comment]
openwrt_s905d_n1_R21.7.15_k5.10.50-flippy-62+-mini.img.gz
244 MB
openwrt_s905d_n1_R21.7.15_k5.10.50-flippy-62+-plus.img.gz
325 MB
openwrt_s905d_n1_R21.7.15_k5.13.2-flippy-62+-mini.img.gz
243 MB
openwrt_s905d_n1_R21.7.15_k5.13.2-flippy-62+-plus.img.gz
324 MB

**Comment by doctor-design** [comment]
@mingxiaoyu
第二遍打包还显示上一次打包内核，可能就是环境没更新（可能是这意思）

**Comment by mingxiaoyu** [comment]
@doctor-design  sudo rm -rf kernel  这个处理方式是没问题的

**Comment by mingxiaoyu** [comment]
我已经修复了shell 版本了

**Comment by hangyubin** [comment]
Error: Error 401: Bad credentials
己设置token
自己上传.config ，打包出现上述错误

**Comment by mingxiaoyu** [comment]
> Error: Error 401: Bad credentials 己设置token 自己上传.config ，打包出现上述错误

两个方案：

1.  token 换成        token: ${{ secrets.GITHUB_TOKEN }}
2. 安装我的token 名字 建立好 放在 secrets. 权限全给
